#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERCENT="${1:-${COMPOSE_MEMORY_PERCENT:-70}}"

if ! [[ "$PERCENT" =~ ^[0-9]+$ ]]; then
    echo "Percent must be an integer between 60 and 80." >&2
    exit 1
fi

if (( PERCENT < 60 || PERCENT > 80 )); then
    echo "Percent must be between 60 and 80." >&2
    exit 1
fi

get_total_memory_mib() {
    if [[ -r /proc/meminfo ]]; then
        awk '/MemTotal:/ {printf "%d\n", $2 / 1024}' /proc/meminfo
        return
    fi

    if command -v sysctl >/dev/null 2>&1; then
        local bytes
        bytes="$(sysctl -n hw.memsize)"
        echo $(( bytes / 1024 / 1024 ))
        return
    fi

    echo "Unable to detect total system memory." >&2
    exit 1
}

write_env_file() {
    local path="$1"
    local prefix="$2"
    cat >"$path" <<EOF
# Auto-generated by src/Docker/apply_compose_memory_limits.sh
# Host memory detected: ${TOTAL_MIB} MiB
# Requested compose memory percent: ${PERCENT}%
LOCAL_UID=${LOCAL_UID}
LOCAL_GID=${LOCAL_GID}
${prefix}_MEM_LIMIT=${LIMIT_MIB}m
${prefix}_MEMSWAP_LIMIT=${LIMIT_MIB}m
EOF
}

TOTAL_MIB="$(get_total_memory_mib)"
LIMIT_MIB=$(( TOTAL_MIB * PERCENT / 100 ))
LOCAL_UID="$(id -u)"
LOCAL_GID="$(id -g)"

write_env_file "${SCRIPT_DIR}/ros/.env" "FRUC_ROS"
write_env_file "${SCRIPT_DIR}/iKalibr/.env" "IKALIBR"
write_env_file "${SCRIPT_DIR}/packet_converter/.env" "PACKET_CONVERTER"
cat >"${SCRIPT_DIR}/rviz/.env" <<EOF
# Auto-generated by src/Docker/apply_compose_memory_limits.sh
LOCAL_UID=${LOCAL_UID}
LOCAL_GID=${LOCAL_GID}
EOF

printf 'Wrote Docker memory limits at %s%% of %s MiB (%s MiB).\n' \
    "$PERCENT" "$TOTAL_MIB" "$LIMIT_MIB"
